### ISSUE TITLE
Municipality registry doesn’t validate: OfficieleTaal or OfficieleTalen?

### ISSUE THREAD

**Issue by pietercolpaert** [ddvlanck/base_registries_event_stream#21]
See
 - https://github.com/ddvlanck/base_registries_event_stream/blob/master/src/municipality-registry/GemeenteUtils.ts#L88
 -  https://github.com/ddvlanck/base_registries_event_stream/blob/master/src/municipality-registry/GemeenteUtils.ts#L139

Same with faciliteitenTalen

**Comment by ddvlanck** [comment]
This was fixed in [release 2.1.1](https://github.com/ddvlanck/base_registries_event_stream/releases/tag/2.1.1)
